<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Default test(failed)" time="0.101" errors="0" timestamp="2023-09-05T08:40:45 IST">
  <testcase classname="testPkg.TestScenario" name="first_testcase" time="0.028">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hello1] but found [Hello]
at testPkg.TestScenario.first_testcase(TestScenario.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testPkg.TestScenario" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testPkg.TestScenario" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testPkg.TestScenario" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testPkg.TestScenario" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testPkg.TestScenario" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
</testsuite> <!-- Default test(failed) -->
